### ISSUE TITLE
How to config PROXY_PASS?

### ISSUE THREAD

**Issue by Tangoes** [toomuchio/plex-nginx-reverseproxy#10]
Hi!

In my domain server.com, I use more than one port (ie: server.com:2020 for plexpy and server.com:3030 for deluge-web)

So, after setting up SSL, all connections to those ports answer with an SSL error, and cannot connect to any web different to PMS. 

I imagine that the last part of the config file, is to fix this, but... can get it working!

Any clue?

BR!
```
#If you want to have plexpy ect.. on the same domain you can achieve it like this.
	#location /plexpy {
	#	proxy_pass http://127.0.0.1:8181;
	#}
```

TL;DR: How to avoid converting HTTP to HTTPS? URL changes from http://server.com:2020 to https://server.com:2020 and fails.

**Comment by sander1** [comment]
Do not set up those backend locations with SSL, use normal http for them. Secure nginx with SSL and use `proxy_pass` like in the example:

```
location /plexpy {
    proxy_pass http://127.0.0.1:8181/xxxxxx;
}
```
where `xxxxxx` is the _HTTP Root_ value set in PlexPy:

![screen shot 2017-03-03 at 17 36 33](https://cloud.githubusercontent.com/assets/104684/23559671/0611b594-0038-11e7-97d1-5314f39f1d1d.jpg)

**Comment by toomuchio** [comment]
Actually you don't add the /xxxx bit, I never have and it works fine for me. Guess it works both ways?

Going to close this issue off, instructions are clear and these follow up instructions make things even clearer. Don't want these the issues up with questions, it's more for tracking bugs and performance issues.

Take a closer read through the instructions next time.
