### ISSUE TITLE
Servers.xml

### ISSUE THREAD

**Issue by hjone72** [toomuchio/plex-nginx-reverseproxy#11]
Hi,

I'm having a strange issue where my server isn't being published to Plex.tv correctly. Just trying to nut out where the problem is.

Does anyone here have their server listed under:
https://plex.tv/pms/servers.xml

May have nothing to do with the configuration here I'm just seeing my server disappear from servers.xml when enabling my firewall.

Thanks,

**Comment by toomuchio** [comment]
Sounds like it's related to your firewall, I block the default port as I advise in the readme and mine appears in the xml without issue.
