### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Suika** [toomuchio/plex-nginx-reverseproxy#12]
I'm running plex on my built NAS that has it's own dns entry. 
For ease of use, I create a hostname pointing to the NAS ip.

And using the current configuration, it, for some reason didn't want to access the Plex Wen Interface.
You get the nice "Please Login" (aka. 401) view, which shouldn't be there since I'm on local network.

I still haven't found a better way around it, but if one sends the Token to Plex as a header, it will work correctly. But it depends if people want to use it like that.

Maybe include it as comment, in case nothing works for other people.
proxy_set_header X-Plex-Token "";

**Comment by hjone72** [comment]
In plex you can specify what networks are considered local and what networks are allowed without Auth. I suspect you will need to just set one of these.

![image](https://cloud.githubusercontent.com/assets/4342811/23681824/4bf3dc7a-03dc-11e7-9907-208a357bbfd7.png)
