### ISSUE TITLE
Multiple Plex Server

### ISSUE THREAD

**Issue by sgu222e** [toomuchio/plex-nginx-reverseproxy#24]
Is it possible to front multiple plex servers through a single nginx reverse proxy?
I'm thinking something like domain.com/server1 and domain.com/server2 or server1.domain.com and server2.domain.com

Thanks

**Comment by toomuchio** [comment]
You can't do it by /server1 as far as I'm aware. But over sub domains yes.

Just build out your config and store it in conf.d/site-available plex1.conf and plex2.conf change the domain it should work fine, you may need to use another name for the upstream block in plex2 however.

But yes, this will work. I was even using nginx to load balance between two identical plex instances on different servers.
