### ISSUE TITLE
Latest update breaks casting?

### ISSUE THREAD

**Issue by hjone72** [toomuchio/plex-nginx-reverseproxy#27]
There is a bit of information in the following thread about the how Plex have changed their method of authenticating.

https://www.reddit.com/r/PleX/comments/71mbsr/plex_inc_just_cost_me_my_favorite_hobby_and/

I just noticed today that casting from my Phone to a chromecast now displays "Media Unavailable".

Are others having this issue too?

**Comment by toomuchio** [comment]
Casting still works fine for me, it's unlikely the authentication would cause any issues for this configuration.

It shouldn't cause issues for anything, and it's a far more secure and better way to handle authentication for Plex.
For example by injecting a bit of javascript with Nginx you can capture all the passwords entered in the login form.

The whole iframe method is a little silly, and with a small tweak all those dashboards would work fine anyway, or they could reverse proxy everything and remove the iframe header..

Will leave this issue open for a few more days, but I'm not aware of any issues.

**Comment by hjone72** [comment]
Appreciate the detailed response. Since you're not getting the issue I'll dive a little deeper. Could be something funky with my configuration.

Thanks

**Comment by toomuchio** [comment]
Nothing new on this so I'll close it off.
