### ISSUE TITLE
NGINX wont start with conf

### ISSUE THREAD

**Issue by dac9** [toomuchio/plex-nginx-reverseproxy#31]
See the error below. Line three and it hits an issue. any ideas?

2018/03/12 16:14:22 [emerg] 2173#0: "ssl_session_cache" directive is not allowed here in /etc/nginx/nginx.conf:3

**Comment by dac9** [comment]
Solved. Had to add some original conf details.

**Comment by Nostang3** [comment]
> 
> 
> Solved. Had to add some original conf details.

Could you expand on this?
