### ISSUE TITLE
Only Allowing Plex Local Access (for readme)

### ISSUE THREAD

**Issue by camjac251** [toomuchio/plex-nginx-reverseproxy#33]
I am unable to edit the readme myself and pull request so I thought that I'd make this issue to let you know about something I found recently [https://forums.plex.tv/discussion/comment/1192684/#Comment_1192684](https://forums.plex.tv/discussion/comment/1192684/#Comment_1192684)

Basically you add in `allowLocalhostOnly="1"` inside of your Preferences.xml, for me I added it before all of the other variables, then restart Plex. After that, my plex had stopped responding to remotely and only worked through local. This can be really helpful for those who don't have access to a firewall or are unable to use the default 32400 port so remote access being disabled works. Since if you use a custom port, it will still leak out.

**Comment by toomuchio** [comment]
Interesting nice find, I guess it switches the listening interface from * to localhost only.

**Comment by toomuchio** [comment]
I'll add this to the readme, and close the issue when I do.

**Comment by camjac251** [comment]
Yeah it's well hidden, there's no other mention on the forums of this variable, as well as on the wiki. And other attempts at trying to bind to localhost on the forums went nowhere last I checked.

**Comment by toomuchio** [comment]
Very handy, added that in I'll have to try it out myself later but I use a firewall for other reasons so it's not an issue for me.
