### ISSUE TITLE
allowLocalhostOnly no longer exists

### ISSUE THREAD

**Issue by zmike808** [toomuchio/plex-nginx-reverseproxy#35]
allowLocalhostOnly no longer exists as a plex option. Trying to set this in Preferences.xml will result in plex failing to start. Which is a shame, since it would have been a nice and convenient alternative to iptables/UFW =(

**Comment by camjac251** [comment]
Are you sure? For me it worked not long ago on linux. Would you mind posting an example of how your Preferences.xml looked? What OS did you use?

**Comment by ghost** [comment]
I did a fresh install of PMS (1.13.1.5063) on linux and the Preferences.xml file does not have an entry for  allowLocalhostOnly.

It seems to have been removed from the wiki:
https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/

**Comment by camjac251** [comment]
It does not exist in the advanced hidden server settings help page, you must add it yourself to the Preferences.xml.

You must add `allowLocalhostOnly="1"` to your `Preferences.xml` in order for it to work correctly.

So something like this `<Preferences allowLocalhostOnly="1" ManualPortMappingMode="1"...`

**Comment by ghost** [comment]
> So something like this <Preferences allowLocalhostOnly="1" ManualPortMappingMode="1"...

Thanks for the clarification. This worked.
