### ISSUE TITLE
Internal Clients reporting 127.0.0.1

### ISSUE THREAD

**Issue by animosity022** [toomuchio/plex-nginx-reverseproxy#36]
I just finally turned off my internal clients and pushed them to using the proxy as well.

I turned on verbose/debug and I can see the header looks good:

```
Aug 29, 2018 14:38:17.702 [0x7f5c13ffc700] VERBOSE -  * X-Real-IP => 192.168.1.105
Aug 29, 2018 14:38:17.702 [0x7f5c13ffc700] VERBOSE -  * X-Forwarded-For => 192.168.1.105
Aug 29, 2018 14:38:17.702 [0x7f5c13ffc700] VERBOSE -  * X-Forwarded-Proto => https
```

But for some odd reason, I'm seeing only the 127 address for the local LAN IPs instead of the internal address. I'm sure I'm missing something silly but can't seem to figure out what it is.

**Comment by animosity022** [comment]
Missed adding in the Tautulli pic.

![image](https://user-images.githubusercontent.com/5088712/44809057-c0ef7800-ab9b-11e8-8310-5e1666743450.png)

**Comment by animosity022** [comment]
Here is an example of external IP:

![image](https://user-images.githubusercontent.com/5088712/44809624-40317b80-ab9d-11e8-842d-bfa31293c650.png)

**Comment by animosity022** [comment]
I'm guessing it has to be plex at this point as the only issues I have are with any private address ranges. I tested on my HomeVPN as well which is on a different subnet:

```
Aug 31, 2018 10:12:05.608 [0x7f7bf93fe700] VERBOSE - X-Forwarded-For: 12.150.5.XXX
Aug 31, 2018 10:12:05.608 [0x7f7bf93fe700] DEBUG - Using X-Forwarded-For: 12.150.5.XXX as remote address

Aug 31, 2018 10:09:28.167 [0x7f7bf43fe700] VERBOSE -  * X-Real-IP => 10.0.8.6
Aug 31, 2018 10:09:28.168 [0x7f7bf43fe700] VERBOSE -  * X-Forwarded-For => 10.0.8.6
Aug 31, 2018 10:09:28.168 [0x7f7bf43fe700] VERBOSE -  * X-Forwarded-Proto => https
```

None of the private IP ranges seem to make the debug message of using the X-Forwarded-For: Anyone else seen this? I can turn back on 32400 locally if that's the case :(

**Comment by toomuchio** [comment]
Seems like a configuration issue perhaps with Plexpy, I'm unable to recreate it.
