### ISSUE TITLE
How do I make this work with /plex instead of a subdomain?

### ISSUE THREAD

**Issue by rcdailey** [toomuchio/plex-nginx-reverseproxy#37]
I want to access plex using `https://domain.com/plex`, instead of `https://plex.domain.com`. How can I achieve this? What parts of your script should I change?

**Comment by toomuchio** [comment]
This isn't a support forum, the config is provided as is, google around for a guide if you don't understand how it works.
Issues are only for issues.

**Comment by thistac** [comment]
Hi! As this repository was the first one suggested by google, maybe others like me will also look for it... I made it work like this:
```
server {

        [...]

        location /plex/ {
                proxy_pass http://plex_backend/;
        }
        if ($http_referer ~ /plex/) {
                rewrite ^/web/(.*) /plex/web/$1? redirect;
        }
}
```
[Refer on reddit](https://www.reddit.com/r/PleX/comments/8r1ngu/getting_plex_ready_behind_a_nginx_reverse_proxy/)
Cheers
