### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by rcdailey** [toomuchio/plex-nginx-reverseproxy#39]
I get the following in nginx:

> letsencrypt    | 2018/12/03 18:25:13 [error] 373#373: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 67.214.81.4, server: plex.domain.com, request: "GET /media/providers?X-Plex-Product=Plex%20Web&X-Plex-Version=3.77.2&X-Plex-Client-Identifier=asdf&X-Plex-Platform=Chrome&X-Plex-Platform-Version=70.0&X-Plex-Sync-Version=2&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1920x978%2C1920x1080&X-Plex-Token=asdf&X-Plex-Language=en HTTP/2.0", upstream: "http://127.0.0.1:32400/media/providers?X-Plex-Product=Plex%20Web&X-Plex-Version=3.77.2&X-Plex-Client-Identifier=asdf&X-Plex-Platform=Chrome&X-Plex-Platform-Version=70.0&X-Plex-Sync-Version=2&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1920x978%2C1920x1080&X-Plex-Token=asdf&X-Plex-Language=en", host: "plex.domain.com", referrer: "https://app.plex.tv/"

Not sure why this is failing. Any help?

**Comment by hjone72** [comment]
The log suggests that there is no server running on 127.0.0.1:32400. Is Plex definitely up and running?

**Comment by rcdailey** [comment]
I switched to `linuxserver/letsencrypt` which has a preset configuration for Plex that is less sophisticated than this one. As such, I am closing this issue since I am no longer having the problem.
