### ISSUE TITLE
CloudFlare Account Disabled - Abuse?

### ISSUE THREAD

**Issue by enz1ey** [toomuchio/plex-nginx-reverseproxy#43]
Just got the following email from CloudFlare:

> Cloudflare has deactivated your website [xxxxx.xxx] from our network for a possible violation of our Terms of Service.
> 
> 
> Your visitors will be routed directly to your origin server, where your website is hosted, and will not
> receive any performance and security benefits from Cloudflare. Cloudflare's Terms of Service are
> available at https://www.cloudflare.com/terms/.
> 
> 
> If you have any questions, please email us at abusereply@cloudflare.com.
> 
> 
> Thank you for using Cloudflare.
> 
> 
> The Cloudflare Team

Anybody else ever see this? I haven't done anything outside of what's in this guide.

**Comment by toomuchio** [comment]
This 'guide'/config's primary purpose has never been to allow you to send stuff via CloudFlare. There was a mention of it very early on in the README as a possible use-case. But was quickly removed.

I've personally never used it on my own stuff, it wouldn't surprise me if it breached TOS.
