### ISSUE TITLE
Plex is not reachable.

### ISSUE THREAD

**Issue by maxisme** [toomuchio/plex-nginx-reverseproxy#45]
Hello,

When trying to access plex through my domain I get:

![image](https://user-images.githubusercontent.com/16902919/71451919-d74d1a00-2776-11ea-8143-12f38c28661b.png)

```
Plex is not reachable.
Make sure your server has an internet connection and any firewalls or other programs are set to allow access.
```

Any ideas how to fix?

Cheers.

**Comment by toomuchio** [comment]
This is not a support forum, the config works as intended you must have misconfigured it.

**Comment by maxisme** [comment]
Thanks
