### ISSUE TITLE
Limited connection or none at all with app clients

### ISSUE THREAD

**Issue by bengalih** [toomuchio/plex-nginx-reverseproxy#46]
I really wanted to avoid opening an issue here, but I really need some assistance as I can't get this working with my config.

I am running NGINX on my router using this exact config.  Plex is hosted on internal Windows server.  I am not using CF (other than as a subdomain host for my LE cert).

The only difference is my ISP blocks 80 so I have NGINX listening on 443.

I can access fine using https://plex.mydomain.com  and https://app.plex.tv.

However when trying to use apps like Android client or Roku I get limited connection (Plex Relay).  Also, this is only if I keep Plex's remote connection enabled (on 443 and without opening up any additional ports).  If I disable the remote connections option then the apps can't get any access at all.  Web access continues to work in either scenario.

Best I can tell, apps should be able to work via https/secure, so me not having port 80 available shouldn't matter.  Most of the posts I've found seem to reference a version of this config so I'm coming here begging for some guidance.

**Comment by toomuchio** [comment]
This is not a support forum, my guess is these apps cannot work unless http is open for some initial check. Forward port 8080 at home and get a cheap VPS and reverse proxy the reverse proxy 8080>80 if your ISP wont allow you to open 80.

In-fact I've stated in the README.md that Roku wont work without http open as well.

**Comment by bengalih** [comment]
> This is not a support forum, my guess is these apps cannot work unless http is open for some initial check. Forward port 8080 at home and get a cheap VPS and reverse proxy the reverse proxy 8080>80 if your ISP wont allow you to open 80.
> 
> In-fact I've stated in the README.md that Roku wont work without http open as well.

I've been troubleshooting this issue for the past week and I've finally come to a solution where all is working.  I'm also happy to say that you are incorrect regarding Roku functionality.

I am currently using Roku and Android through only 443 proxied through my NGINX configuration.
My final solution is [here](https://forums.plex.tv/t/unknown-bug-with-remote-access-apps-roku-android-etc-architectural-guidance-with-proxy-cloudflare/524941/7), which will also have links to go back to discuss the issue in more depth.

I appreciate your effort in compiling this template, but it appears there are still some misconceptions about how all this can work.  I'm glad I've finally resolved them on my end.
