### ISSUE TITLE
Config works for webbrowers, not Plex iOS app?

### ISSUE THREAD

**Issue by Kopertje** [toomuchio/plex-nginx-reverseproxy#48]
Hi there!

When i connect to my domain through my reverse proxy (Nginx) with the iOS app, it doesnt work. When i go to my domain in Firefox or Safari on my iPhone, it works fine. Are there any special settings i didnt configure right?

Regards,
Graxo

**Comment by bengalih** [comment]
@Kopertje This might help you along with my linked post on the Plex forums:
https://www.reddit.com/r/PleX/comments/ehd61b/plex_remote_access_via_nginx_reverse_proxy/
