### ISSUE TITLE
Client IP shown as NGINX IP

### ISSUE THREAD

**Issue by jkristoph** [toomuchio/plex-nginx-reverseproxy#54]
Hello,

I have successfully configured nginx reverse proxy with your config and guide but i cannot figure out for the life of me why all client IP under plex show as the nginx IP.....

#Forward real ip and host to Plex
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        #When using ngx_http_realip_module change $proxy_add_x_forwarded_for to '$http_x_forwarded_for,$realip_remote_addr'
        proxy_set_header X-Forwarded-For $http_x_forwarded_for,$realip_remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Sec-WebSocket-Extensions $http_sec_websocket_extensions;
        proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
        proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;

Would appreciate the help

**Comment by minds3t** [comment]
Having the same issue. How can we fix it?
