### ISSUE TITLE
Not working with Plex for Kodi

### ISSUE THREAD

**Issue by natoriousbigg** [toomuchio/plex-nginx-reverseproxy#6]
I'm not sure if it's related to TLS/SS, port, or client detection, but this set up isn't working for Plex for Kodi. Not quite sure how to troubleshoot.

**Comment by toomuchio** [comment]
That's odd... Paste some access logs from when it's trying to access the page here, redact your tokens and IPs of course.

**Comment by sander1** [comment]
I do have this working with Kodi (17.0) and Plex for Kodi (0.0.101) on my Mac (OSX 10.11.6) and Plex (1.3.4) on a remote Ubuntu server with this nginx reverse proxy in front of it.

What is your setup?

**Comment by natoriousbigg** [comment]
@sander1 Do you have remote access and port 32400 opened? It'll work for me if I have port 32400 but of course it's not going thru Cloudflare CDN.

**Comment by toomuchio** [comment]
Is it just Kodi with Plex not working or the entire thing as a whole? Try it in your browser by going to your plex domain on 443 you should hit the /web UI.

**Comment by natoriousbigg** [comment]
@sander1 You're right. I upgrade from Kodi 16.1 Jarvis to Kodi 17.0 and it works now. Looks like the issue it only specific to Kodi 16.1

**Comment by toomuchio** [comment]
I'll close this off then
