### ISSUE TITLE
Plex still connecting throught port 32400

### ISSUE THREAD

**Issue by Tangoes** [toomuchio/plex-nginx-reverseproxy#9]
Hi! 

I followed your nginx conf, and all worked like a charm, except one part:

Plex is still making direct connections in port 32400. When opening chrome console, I can read:

[Connections] Server Plex connected at https://522-14-247-211.3b13bacsdf4131412362b44360d47eaa7.plex.direct:32400/

I set up to allow ONLY secure connections...

Edit: I forgot to ask: Any clue?

**Comment by hjone72** [comment]
You can disable remove access via your server settings. This should prevent your server from accepting connections on 32400. Alternatively you can use your firewall to block connections on port 32400.

![image](https://cloud.githubusercontent.com/assets/4342811/23483938/9eebe0a0-ff20-11e6-9196-64ce057fb85b.png)

**Comment by Tangoes** [comment]
Hi hjone72, the more I configure plex, the more I want to kill it with fire. 

![1488409538](https://cloud.githubusercontent.com/assets/19514845/23486378/1410dd7c-fee0-11e6-9f94-2b6ad38fbda1.png)

(In the image you can see the button ENABLE REMOTE ACCESS, but the green tick... WTF?)

In the other hand, if I drop all connections to port 32400 (using iptables), the server goes down, no connection at all.

**Comment by sander1** [comment]
See the README file, if you setup an nginx reverse proxy set the following in Plex:

- Remote Access: disable (our reverse proxy gives access to our Plex server, so we don't need Plex to do that for us too);
- Set your Custom server access URL in Network > Custom server access URLs (e.g. `https://<your-domain>:443`);
- Open the correct port(s) on your firewall and block everything else.
